apiVersion: v1
kind: Service
metadata:
  name: adsdevicesnpservice-srv
spec:
  type: NodePort
  selector:
    app: adsdevicesservice
  ports:
    - name: adsdevicesservice
      protocol: TCP
      port: 80
      targetPort: 80